apiVersion: v1
kind: Service
metadata:
  name: svc-api-gateway
  labels:
    version: test
spec:
  selector:
    app: api-gateway
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dep-api-gateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: [CONTAINER_REGISTRY]/api-gateway:#{Build.BuildNumber}#
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acrconnection
      nodeSelector:
          beta.kubernetes.io/os: linux
